### ISSUE TITLE
Publish per Tenant App

### ISSUE THREAD

**Issue by antonyotto** [kine/MSDYN365BC_Yaml#8]
Hi Kine,

thanks for the tools.
I'm trying to setup the pipelines to publish App to online sandbox. I received below error in the pipeline and the App is successfully published. Any idea why ?

Thanks.

020-04-23T05:46:24.6853430Z ##[debug]Caught exception from task script.
2020-04-23T05:46:24.6885409Z ##[debug]Error record:
2020-04-23T05:46:24.8596776Z ##[debug]Get-ALAppPublicationStatus : Cannot index into a null array.
2020-04-23T05:46:24.8610876Z ##[debug]At C:\Users\xxxx\Documents\WindowsPowerShell\Modules\NVRAppDevOps\1.0.10\Upload-PerTenantApp.ps1:35 char:23
2020-04-23T05:46:24.8624420Z ##[debug]+ ...   $Status = Get-ALAppPublicationStatus -AppId $AppId -AppSecret $AppS ...
2020-04-23T05:46:24.8638220Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-04-23T05:46:24.8659418Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Get-ALAppPublicationStatus], RuntimeException
2020-04-23T05:46:24.8673187Z ##[debug]    + FullyQualifiedErrorId : NullArray,Get-ALAppPublicationStatus
2020-04-23T05:46:24.8687722Z ##[debug] 
2020-04-23T05:46:24.8713010Z ##[debug]Script stack trace:
2020-04-23T05:46:24.8746510Z ##[debug]at Get-ALAppPublicationStatus, C:\Users\xx\Documents\WindowsPowerShell\Modules\NVRAppDevOps\1.0.10\Get-ALAppPublicationStatus.ps1: line 35
2020-04-23T05:46:24.8759320Z ##[debug]at Upload-PerTenantApp, C:\Users\xxx\Documents\WindowsPowerShell\Modules\NVRAppDevOps\1.0.10\Upload-PerTenantApp.ps1: line 35
2020-04-23T05:46:24.8774389Z ##[debug]at <ScriptBlock>, C:\Users\xxx\Downloads\vsts-agent-win-x64-2.165.2\_work\_tasks\publishbcapppertenant_047393e1-82e4-4d24-8275-237409bb378e\1.0.3\publishtenanttask.ps1: line 27
2020-04-23T05:46:24.8787079Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-04-23T05:46:24.8801035Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-04-23T05:46:24.8821032Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-04-23T05:46:24.8835506Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-04-23T05:46:24.8861615Z ##[debug]Exception:
2020-04-23T05:46:24.8914370Z ##[debug]System.Management.Automation.RuntimeException: Cannot index into a null array.
2020-04-23T05:46:24.8926562Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2020-04-23T05:46:24.8943100Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2020-04-23T05:46:24.8958536Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-04-23T05:46:24.8974329Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-04-23T05:46:24.8991809Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2020-04-23T05:46:24.9006563Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2020-04-23T05:46:24.9018984Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2020-04-23T05:46:24.9033338Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2020-04-23T05:46:24.9045536Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-04-23T05:46:24.9331913Z ##[error]Cannot index into a null array.
2020-04-23T05:46:24.9342420Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot index into a null array.
2020-04-23T05:46:24.9344123Z ##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by kine** [comment]
Hello @antonyotto ,
the reason is, that there is call reading companies from the environment and it has returned no companies from some reason. Try to run this manually:

````
$Token = Get-OAuth2 -AppId $AppId -AppSecret $AppSecret -Credentials $Credentials -Tenant $Tenant
Get-BCAPIData -OAuthToken $Token -Tenant $Tenant -APIUri $APIUri -Query 'companies' -Environment $Environment -APIVersion $APIVersion
````
It should return at least one company.

**Comment by kine** [comment]
Hi @antonyotto,
have re-read the log you sent and it seems that the problem is, that the call reading the status have not returned anything. It could be some timing issue or I do not know. Will try on my side. Have it worked before? Are you getting this each time or when you re-run the stage it goes trough?

**Comment by kine** [comment]
Hmm... unable to test on my side, because we have activated MFA on our users accounts to fulfill MS requirements and thus I am unable to publish the apps from pipeline (no support for service accounts yet and the current way doesn't support MFA). This is rendering the Password Grant OAuth unusable (but of course, it was never recommended to use this grant type, but it was only possible way).

**Comment by antonyotto** [comment]
Hi Kine,
Thanks for the reply, this is the first time I used it and I tried few times but the result is the same 
I will try to run it directly from Powershell and see if it work.

Thanks,

**Comment by antonyotto** [comment]
It works if I directly use powershell script instead of using task publishbcapppertenant

Upload-PerTenantApp -AppId [xx] -AppSecret [xx] -Tenant [xx] -AppPath "C:\artifact\Default publisher_TestBuild_1.4.0.0.app" -Environment Sandbox -APIVersion v1.0 -Credential $mycreds -WaitForResult
Getting OAuth token...
Getting companies...
Getting uploading extension to company 83b8f35c-fb52-ea11-bb59-00155df3a615 (CRONUS NZ)...
Getting last publishing status from company 83b8f35c-fb52-ea11-bb59-00155df3a615...
Last status: TestBuild Default publisher 1.4.0.0 InProgress
Getting last publishing status from company 83b8f35c-fb52-ea11-bb59-00155df3a615...
Last status: TestBuild Default publisher 1.4.0.0 InProgress
Getting last publishing status from company 83b8f35c-fb52-ea11-bb59-00155df3a615...
Last status: TestBuild Default publisher 1.4.0.0 InProgress
Getting last publishing status from company 83b8f35c-fb52-ea11-bb59-00155df3a615...
Last status: TestBuild Default publisher 1.4.0.0 Completed

**Comment by kine** [comment]
Ok. If it works manually and not in pipeline, than double check that all parameters in the pipelines are passed correctly. Are you using your own agent or hosted?

**Comment by antonyotto** [comment]
I'm using my own agent. it's the same server that I used to run the powershell.

I also try to run the powershell in the pipeline and it works

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by kine** [comment]
Ok, than the problem must be in the parameters of the step. Could you send me log from the pipeline? I want to see the xxxx-expanded.yaml file from the full logs.

**Comment by antonyotto** [comment]
Sorry. I have remove the pipeline. I will re-create it and send you the log. thanks
